/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.qc.bdeb.c37.semaine5.exercice1;
import ca.qc.bdeb.c37.semaine3.exercice3.Fraction;

/**
 *
 * @author paulwillyjean
 */
public class Calculatrice extends javax.swing.JApplet {

	Fraction fractionUn = new Fraction();
	Fraction fractionDeux = new Fraction();

	/**
	 * Initializes the applet Calculatrice
	 */
	@Override
	public void init() {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the applet */
		try {
			java.awt.EventQueue.invokeAndWait(new Runnable() {
				public void run() {
					initComponents();
				}
			});
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}

	/**
	 * This method is called from within the init() method to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfResultat = new javax.swing.JTextField();
        lFractionUn = new javax.swing.JLabel();
        tfFractionUn = new javax.swing.JTextField();
        tfFractionDeux = new javax.swing.JTextField();
        lFractionDeux = new javax.swing.JLabel();
        bAddition = new javax.swing.JButton();
        bSoustraction = new javax.swing.JButton();
        bMultiplication = new javax.swing.JButton();
        bDivision = new javax.swing.JButton();
        bEffacer = new javax.swing.JButton();

        tfResultat.setEditable(false);

        lFractionUn.setText("Fraction1");

        tfFractionUn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFractionUnFocusLost(evt);
            }
        });

        tfFractionDeux.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFractionDeuxFocusLost(evt);
            }
        });

        lFractionDeux.setText("Fraction2");

        bAddition.setText("Addition");
        bAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdditionActionPerformed(evt);
            }
        });

        bSoustraction.setText("Soustraction");
        bSoustraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSoustractionActionPerformed(evt);
            }
        });

        bMultiplication.setText("Multiplication");
        bMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMultiplicationActionPerformed(evt);
            }
        });

        bDivision.setText("Division");
        bDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDivisionActionPerformed(evt);
            }
        });

        bEffacer.setText("Effacer");
        bEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEffacerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEffacer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfResultat)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bSoustraction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bAddition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lFractionUn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFractionUn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lFractionDeux, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFractionDeux, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bDivision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfResultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfFractionUn)
                        .addComponent(lFractionUn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfFractionDeux)
                        .addComponent(lFractionDeux, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddition)
                    .addComponent(bMultiplication))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSoustraction)
                    .addComponent(bDivision))
                .addGap(18, 18, 18)
                .addComponent(bEffacer)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMultiplicationActionPerformed
		this.tfResultat.setText(this.fractionUn.mult(fractionDeux).toString());
    }//GEN-LAST:event_bMultiplicationActionPerformed

    private void tfFractionUnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFractionUnFocusLost
		javax.swing.JTextField controle = (javax.swing.JTextField) evt.getSource();
		this.fractionUn = new Fraction(controle.getText());
    }//GEN-LAST:event_tfFractionUnFocusLost

    private void bAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdditionActionPerformed
        this.tfResultat.setText(this.fractionUn.plus(fractionDeux).toString());
    }//GEN-LAST:event_bAdditionActionPerformed

    private void bSoustractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSoustractionActionPerformed
        this.tfResultat.setText(this.fractionUn.moins(fractionDeux).toString());
    }//GEN-LAST:event_bSoustractionActionPerformed

    private void tfFractionDeuxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFractionDeuxFocusLost
		javax.swing.JTextField controle = (javax.swing.JTextField) evt.getSource();
		this.fractionDeux = new Fraction(controle.getText());
    }//GEN-LAST:event_tfFractionDeuxFocusLost

    private void bEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEffacerActionPerformed
		tfResultat.setText(null);
		tfFractionUn.setText(null);
		tfFractionDeux.setText(null);
		this.fractionUn = new Fraction();
		this.fractionDeux = new Fraction();
    }//GEN-LAST:event_bEffacerActionPerformed

    private void bDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDivisionActionPerformed
		this.tfResultat.setText(this.fractionUn.div(fractionDeux).toString());
    }//GEN-LAST:event_bDivisionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddition;
    private javax.swing.JButton bDivision;
    private javax.swing.JButton bEffacer;
    private javax.swing.JButton bMultiplication;
    private javax.swing.JButton bSoustraction;
    private javax.swing.JLabel lFractionDeux;
    private javax.swing.JLabel lFractionUn;
    private javax.swing.JTextField tfFractionDeux;
    private javax.swing.JTextField tfFractionUn;
    private javax.swing.JTextField tfResultat;
    // End of variables declaration//GEN-END:variables
}
