/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.qc.bdeb.c37.travailPratique1;

import javax.swing.JOptionPane;

/**
 *
 * @author 1022680
 */
public class TravailPratique extends javax.swing.JFrame {

    /**
     * Creates new form TravailPratique
     */
    public TravailPratique() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCanvas = new ca.qc.bdeb.c37.travailPratique1.JPuzzleCanvas(4, 4);
        jMenuBar = new javax.swing.JMenuBar();
        jMenuBarJeu = new javax.swing.JMenu();
        jMenuItemRedemarrer = new javax.swing.JMenuItem();
        jMenuBarNiveau = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItemScores = new javax.swing.JMenuItem();
        jMenuItemQuitter = new javax.swing.JMenuItem();
        jMenuBarAide = new javax.swing.JMenu();
        jMenuItemInstructions = new javax.swing.JMenuItem();
        jMenuItemAPropos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelCanvasLayout = new javax.swing.GroupLayout(jPanelCanvas);
        jPanelCanvas.setLayout(jPanelCanvasLayout);
        jPanelCanvasLayout.setHorizontalGroup(
            jPanelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanelCanvasLayout.setVerticalGroup(
            jPanelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenuBarJeu.setText("Jeu");

        jMenuItemRedemarrer.setText("Redémarrer");
        jMenuBarJeu.add(jMenuItemRedemarrer);

        jMenuBarNiveau.setText("Niveau");

        jMenuItem1.setText("3 X 3");
        jMenuBarNiveau.add(jMenuItem1);

        jMenuItem2.setText("4 X 4");
        jMenuBarNiveau.add(jMenuItem2);

        jMenuItem3.setText("5 X 5");
        jMenuBarNiveau.add(jMenuItem3);

        jMenuItem4.setText("6 X 6");
        jMenuBarNiveau.add(jMenuItem4);

        jMenuItem5.setText("7 X 7");
        jMenuBarNiveau.add(jMenuItem5);

        jMenuItem6.setText("8 X 8");
        jMenuBarNiveau.add(jMenuItem6);

        jMenuItem7.setText("9 X 9");
        jMenuBarNiveau.add(jMenuItem7);

        jMenuItem8.setText("10 X 10");
        jMenuBarNiveau.add(jMenuItem8);

        jMenuBarJeu.add(jMenuBarNiveau);

        jMenuItemScores.setText("Scores élevés");
        jMenuBarJeu.add(jMenuItemScores);

        jMenuItemQuitter.setText("Quitter");
        jMenuItemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitterActionPerformed(evt);
            }
        });
        jMenuBarJeu.add(jMenuItemQuitter);

        jMenuBar.add(jMenuBarJeu);

        jMenuBarAide.setText("Aide");

        jMenuItemInstructions.setText("Instructions");
        jMenuBarAide.add(jMenuItemInstructions);

        jMenuItemAPropos.setText("À propos");
        jMenuItemAPropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAProposActionPerformed(evt);
            }
        });
        jMenuBarAide.add(jMenuItemAPropos);

        jMenuBar.add(jMenuBarAide);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAProposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAProposActionPerformed
        String message = "Ceci est le travail pratique de Paul-Willy Jean.\n"
                + "Il est fait dans le cadre du cours de programmation orientée"
                + " objet.";
        JOptionPane.showMessageDialog(this, message, "À propos de moi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemAProposActionPerformed

    private void jMenuItemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitterActionPerformed
        // TODO add your handling code here:
		System.exit(0);
    }//GEN-LAST:event_jMenuItemQuitterActionPerformed

	private void setNouvellePartie(int height, int width) {
		this.jPanelCanvas = new JPuzzleCanvas(height, width);
	}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravailPratique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravailPratique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravailPratique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravailPratique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravailPratique().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuBarAide;
    private javax.swing.JMenu jMenuBarJeu;
    private javax.swing.JMenu jMenuBarNiveau;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemAPropos;
    private javax.swing.JMenuItem jMenuItemInstructions;
    private javax.swing.JMenuItem jMenuItemQuitter;
    private javax.swing.JMenuItem jMenuItemRedemarrer;
    private javax.swing.JMenuItem jMenuItemScores;
    private javax.swing.JPanel jPanelCanvas;
    // End of variables declaration//GEN-END:variables
}
